### ISSUE TITLE
Permit count exceeded error

### ISSUE THREAD

**Issue by sjones4** [ha-jdbc/ha-jdbc#96]
Using v3.0.2 the following error is sometimes seen on a busy system around when long running transactions get closed by proxools connection management (maximum-active-time):

```
2015-08-07 01:05:43 ERROR | java.lang.Error: Maximum permit count exceeded
java.lang.Error: Maximum permit count exceeded
        at java.util.concurrent.Semaphore$Sync.tryReleaseShared(Semaphore.java:197)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.releaseShared(AbstractQueuedSynchronizer.java:1340)
        at java.util.concurrent.Semaphore.release(Semaphore.java:431)
        at net.sf.hajdbc.lock.semaphore.SemaphoreLock.unlock(SemaphoreLock.java:92)
        at net.sf.hajdbc.sql.LocalTransactionContext.unlock(LocalTransactionContext.java:190)
        at net.sf.hajdbc.sql.LocalTransactionContext$2.invoke(LocalTransactionContext.java:104)
        at net.sf.hajdbc.sql.AbstractInvocationHandler.invokeOnProxy(AbstractInvocationHandler.java:95)
        at net.sf.hajdbc.sql.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:85)
        at net.sf.hajdbc.sql.ChildInvocationHandler.invoke(ChildInvocationHandler.java:44)
        at com.sun.proxy.$Proxy151.executeBatch(Unknown Source)
        at sun.reflect.GeneratedMethodAccessor186.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.logicalcobwebs.proxool.ProxyStatement.invoke(ProxyStatement.java:100)
        at org.logicalcobwebs.proxool.ProxyStatement.intercept(ProxyStatement.java:57)
        at $java.io.Serializable$$EnhancerByProxool$$76ff8dad.executeBatch(<generated>)
        at org.hibernate.engine.jdbc.batch.internal.BatchingBatch.performExecution(BatchingBatch.java:110)
        at org.hibernate.engine.jdbc.batch.internal.BatchingBatch.doExecuteBatch(BatchingBatch.java:101)
        at org.hibernate.engine.jdbc.batch.internal.AbstractBatchImpl.execute(AbstractBatchImpl.java:149)
        at org.hibernate.engine.jdbc.internal.JdbcCoordinatorImpl.executeBatch(JdbcCoordinatorImpl.java:198)
        at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:372)
        at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:287)
        at org.hibernate.event.internal.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:339)
        at org.hibernate.event.internal.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:52)
        at org.hibernate.internal.SessionImpl.flush(SessionImpl.java:1234)
```

it looks like it may be the case that unlock in LocalTransactionContext needs updating to handle the connection being closed from another thread?

**Comment by pferraro** [comment]
Hmm.  That shouldn't be - the reference to the LocalTransactionContext is
held by the connection proxy, not in any thread local storage.
Consequently, there should be no problem if the Connection.close() occurs
from another thread.  However, there may be some asymmetric lock/unlock
getting triggered. I'll take a closer look.

Paul
